# Generated by Django 3.2.4 on 2021-06-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastRentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_bg', models.ImageField(upload_to='home_car_bg')),
                ('title', models.CharField(max_length=50)),
                ('doors', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'fast rent',
                'verbose_name_plural': 'fast rents',
            },
        ),
    ]
