# Generated by Django 3.2.4 on 2021-06-13 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_fastrentmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastrentmodel',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
