# Generated by Django 3.2.4 on 2021-06-14 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210614_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_step', models.TextField()),
                ('second_step', models.TextField()),
                ('third_step', models.TextField()),
                ('fourth_step', models.TextField()),
                ('fifth_step', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'step',
                'verbose_name_plural': 'steps',
            },
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
