# Generated by Django 3.2.4 on 2021-06-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210614_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeUserCommentImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user opinion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user image',
                'verbose_name_plural': 'users images',
            },
        ),
        migrations.CreateModel(
            name='HomeUserCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'home comment',
                'verbose_name_plural': 'home comments',
            },
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='FastRentModel',
        ),
        migrations.DeleteModel(
            name='ServiceModel',
        ),
        migrations.DeleteModel(
            name='StepsModel',
        ),
        migrations.AddField(
            model_name='homeusercommentimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.homeusercommentmodel'),
        ),
    ]
