# Generated by Django 3.2.4 on 2021-06-16 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210616_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeusercommentmodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user_opinion_images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HomeUserCommentImageModel',
        ),
    ]
