# Generated by Django 3.2.4 on 2021-06-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210616_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeUserCommentModel',
            new_name='CommentModel',
        ),
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
