# Generated by Django 3.2.4 on 2021-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210618_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contact_bg_image')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact home image',
                'verbose_name_plural': 'contacts home image',
            },
        ),
    ]
