# Generated by Django 3.2.4 on 2021-06-19 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_opinionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='opinion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.opinionmodel'),
        ),
    ]
