# Generated by Django 3.2.4 on 2021-06-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_commentmodel_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='opinion',
        ),
        migrations.DeleteModel(
            name='OpinionModel',
        ),
    ]
