# Generated by Django 3.2.4 on 2021-06-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210619_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
