# Generated by Django 3.2.4 on 2021-06-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_delete_commentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_bg_image')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'home image',
                'verbose_name_plural': 'home image',
            },
        ),
    ]
