# Generated by Django 3.2.4 on 2021-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_contactimagemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactimagemodel',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='homeimagemodel',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
