# Generated by Django 3.2.5 on 2021-07-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210727_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactimagemodel',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='contactimagemodel',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='contactinfomodel',
            name='address_en',
            field=models.CharField(max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contactinfomodel',
            name='address_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='homeimagemodel',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='homeimagemodel',
            name='title_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
    ]
