# Generated by Django 3.2.5 on 2021-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20210729_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfomodel',
            name='email_en',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='contactinfomodel',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
    ]
