# Generated by Django 3.2.5 on 2021-07-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20210730_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfomodel',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='contactinfomodel',
            name='email_ru',
        ),
    ]
