# Generated by Django 3.2.4 on 2021-06-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images')),
                ('title', models.CharField(max_length=35)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=15)),
                ('doors', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarsImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_bg_image')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'car home picture',
                'verbose_name_plural': 'cars home pictures',
            },
        ),
        migrations.CreateModel(
            name='IconModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'icon',
                'verbose_name_plural': 'icons',
            },
        ),
        migrations.CreateModel(
            name='ServicesImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services_bg_image')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'services home image',
                'verbose_name_plural': 'services home images',
            },
        ),
    ]
