# Generated by Django 3.2.4 on 2021-06-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20210616_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsimagemodel',
            options={'verbose_name': 'car home image', 'verbose_name_plural': 'cars home image'},
        ),
        migrations.AlterModelOptions(
            name='servicesimagemodel',
            options={'verbose_name': 'services home image', 'verbose_name_plural': 'services home image'},
        ),
    ]
