# Generated by Django 3.2.4 on 2021-06-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20210616_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IconModel',
        ),
    ]
