# Generated by Django 3.2.4 on 2021-06-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_delete_iconmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
