# Generated by Django 3.2 on 2021-06-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20210622_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doormodel',
            old_name='doors',
            new_name='door',
        ),
        migrations.RenameField(
            model_name='seatmodel',
            old_name='seats',
            new_name='seat',
        ),
    ]
