# Generated by Django 3.2 on 2021-06-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20210623_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
