# Generated by Django 3.2 on 2021-06-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_carmodel_doormodel_seatmodel_transmissionmodel_typemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doormodel',
            old_name='door',
            new_name='doors',
        ),
        migrations.RenameField(
            model_name='seatmodel',
            old_name='seat',
            new_name='seats',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='doors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='offers.doormodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='offers.seatmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='offers.transmissionmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='offers.typemodel'),
        ),
    ]
