# Generated by Django 3.2 on 2021-06-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_auto_20210623_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='doors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.doormodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.seatmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.transmissionmodel'),
        ),
    ]
