# Generated by Django 3.2 on 2021-06-26 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_alter_typemodel_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doormodel',
            options={'verbose_name': 'door', 'verbose_name_plural': 'doors'},
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='offers.typemodel'),
        ),
        migrations.AlterField(
            model_name='typemodel',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
