# Generated by Django 3.2 on 2021-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_auto_20210626_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodel',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
