# Generated by Django 3.2 on 2021-06-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_alter_typemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='doors',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='DoorModel',
        ),
        migrations.DeleteModel(
            name='SeatModel',
        ),
        migrations.DeleteModel(
            name='TransmissionModel',
        ),
        migrations.DeleteModel(
            name='TypeModel',
        ),
    ]
