# Generated by Django 3.2 on 2021-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_auto_20210626_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
