# Generated by Django 3.2 on 2021-06-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_alter_carmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
