# Generated by Django 3.2 on 2021-06-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_alter_carmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doors', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'door',
                'verbose_name_plural': 'doors',
            },
        ),
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'seat',
                'verbose_name_plural': 'seats',
            },
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'transmission',
                'verbose_name_plural': 'transmissions',
            },
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='doors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.doormodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.seatmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.transmissionmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.typemodel'),
        ),
    ]
