# Generated by Django 3.2 on 2021-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0022_auto_20210626_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmodel',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
