# Generated by Django 3.2 on 2021-06-26 15:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0023_alter_seatmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
