# Generated by Django 3.2 on 2021-06-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0025_auto_20210627_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='BrandModel',
        ),
    ]
