# Generated by Django 3.2 on 2021-06-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0026_auto_20210627_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
