# Generated by Django 3.2.4 on 2021-06-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0030_auto_20210627_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
