# Generated by Django 3.2 on 2021-06-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0031_auto_20210627_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fuel',
                'verbose_name_plural': 'fuel',
            },
        ),
        migrations.CreateModel(
            name='PowerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'power',
                'verbose_name_plural': 'power',
            },
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='seats',
        ),
        migrations.DeleteModel(
            name='DoorModel',
        ),
        migrations.DeleteModel(
            name='SeatModel',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.fuelmodel'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.powermodel'),
        ),
    ]
