# Generated by Django 3.2 on 2021-06-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0032_auto_20210630_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.powermodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.yearmodel'),
        ),
        migrations.AlterField(
            model_name='powermodel',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='yearmodel',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
