# Generated by Django 3.2 on 2021-06-30 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0033_auto_20210630_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'drive',
                'verbose_name_plural': 'drive',
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.drivemodel'),
        ),
    ]
