# Generated by Django 3.2 on 2021-06-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0034_auto_20210630_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.drivemodel'),
        ),
        migrations.AlterField(
            model_name='drivemodel',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
