# Generated by Django 3.2.5 on 2021-07-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0035_auto_20210630_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
