# Generated by Django 3.2.5 on 2021-07-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0036_carmodel_car_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='car_title',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.brandmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
