# Generated by Django 3.2.5 on 2021-07-04 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0037_auto_20210705_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.brandmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
