# Generated by Django 3.2.5 on 2021-07-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0038_auto_20210705_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.fuelmodel'),
        ),
    ]
