# Generated by Django 3.2.5 on 2021-07-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0039_alter_carmodel_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.fuelmodel'),
        ),
    ]
