# Generated by Django 3.2.5 on 2021-07-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0040_alter_carmodel_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelmodel',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
