# Generated by Django 3.2.5 on 2021-07-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0041_alter_fuelmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='offers.fuelmodel'),
        ),
        migrations.AlterField(
            model_name='fuelmodel',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
