# Generated by Django 3.2.5 on 2021-07-29 15:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0045_auto_20210727_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='title_en',
            field=models.CharField(max_length=20, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='title_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='title_en',
            field=models.CharField(max_length=40, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='title_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='carsimagemodel',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='carsimagemodel',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='drivemodel',
            name='title_en',
            field=models.CharField(max_length=15, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='drivemodel',
            name='title_ru',
            field=models.CharField(max_length=15, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='fuelmodel',
            name='title_en',
            field=models.CharField(max_length=20, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='fuelmodel',
            name='title_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='powermodel',
            name='amount_en',
            field=models.PositiveIntegerField(null=True, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='powermodel',
            name='amount_ru',
            field=models.PositiveIntegerField(null=True, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='servicesimagemodel',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicesimagemodel',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='transmissionmodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='transmissionmodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='typemodel',
            name='title_en',
            field=models.CharField(max_length=15, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='typemodel',
            name='title_ru',
            field=models.CharField(max_length=15, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='title_en',
            field=models.PositiveIntegerField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='title_ru',
            field=models.PositiveIntegerField(null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
    ]
