# Generated by Django 3.2.5 on 2021-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0046_auto_20210729_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='brandmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='powermodel',
            name='amount_en',
        ),
        migrations.RemoveField(
            model_name='powermodel',
            name='amount_ru',
        ),
        migrations.RemoveField(
            model_name='yearmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='yearmodel',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
