# Generated by Django 3.2.5 on 2021-08-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0047_auto_20210730_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images', verbose_name='image')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.carmodel', verbose_name='car')),
            ],
            options={
                'verbose_name': 'car image',
                'verbose_name_plural': 'car images',
            },
        ),
    ]
