# Generated by Django 3.2.5 on 2021-08-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0049_carmodel_real_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='real_price',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
    ]
