# Generated by Django 3.2.4 on 2021-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_bg_image')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'blog home image',
                'verbose_name_plural': 'blog home image',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts_images')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutimagemodel',
            options={'verbose_name': 'about home image', 'verbose_name_plural': 'about home image'},
        ),
        migrations.AlterModelOptions(
            name='historymodel',
            options={'verbose_name': 'history', 'verbose_name_plural': 'history'},
        ),
        migrations.AlterModelOptions(
            name='infomodel',
            options={'verbose_name': 'info', 'verbose_name_plural': 'info'},
        ),
        migrations.AlterModelOptions(
            name='teemmodel',
            options={'verbose_name': 'teem', 'verbose_name_plural': 'teem'},
        ),
    ]
