# Generated by Django 3.2.4 on 2021-06-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_teemmodel_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutAuthorModel',
        ),
    ]
