# Generated by Django 3.2.4 on 2021-06-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_delete_aboutauthormodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
