# Generated by Django 3.2.4 on 2021-06-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_commentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='message',
            new_name='comment',
        ),
    ]
