# Generated by Django 3.2.5 on 2021-07-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20210626_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeemModel',
            new_name='TeamModel',
        ),
        migrations.AlterModelOptions(
            name='teammodel',
            options={'verbose_name': 'team', 'verbose_name_plural': 'team'},
        ),
    ]
