# Generated by Django 3.2.5 on 2021-07-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210705_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraParagraphModel',
        ),
    ]
