# Generated by Django 3.2.5 on 2021-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='date_to',
            field=models.DateTimeField(null=True),
        ),
    ]
