# Generated by Django 3.2.5 on 2021-08-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210806_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date_from',
            field=models.DateTimeField(null=True, verbose_name='date_from'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date_to',
            field=models.DateTimeField(null=True, verbose_name='date_to'),
        ),
    ]
